[context.production.environment]
  HUGO_VERSION = "0.83.1"

[[redirects]]
from = "https://justalever.com/foli"
to = "https://work.justalever.com"
status = 301
force = true

[[redirects]]
from = "https://justalever.com/work"
to = "https://work.justalever.com"
status = 301
force = true

[[redirects]]
from = "https://justalever.com/resume"
to = "https://www.craft.me/s/6tTdmDYGFbCJiZ"
status = 301
force = true
